---
namespace: mcfitz2
name: libguestfs
version: 1.2.0
readme: README.md
authors:
  - Vadim Khitrin <me@vkhitrin>
  - Micah Fitzgerald <mcfitz2@gmail.com>
description: libguestfs Ansible modules
license_file: COPYING.md
tags:
  - libguestfs
repository: https://github.com/mcfitz2/ansible-libguestfs-collection
documentation: https://github.com/mcfitz2/ansible-libguestfs-collection/tree/main/docs
homepage: https://github.com/mcfitz2/ansible-libguestfs-collection
issues: https://github.com/mcfitz2/ansible-libguestfs-collection/issues?q=is%3Aissue+is%3Aopen
build_ignore:
  - "*.tar.gz"
  - ".gitignore"
